### ISSUE TITLE
SDK is expecting different JSON schema for ListAuthenticationMethods API endpoint

### ISSUE THREAD

**Issue by mparz111** [auth0/go-auth0#240] opened 2023-07-13 21:26 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/go-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://pkg.go.dev/github.com/auth0/go-auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/go-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/go-auth0/releases/latest) of this SDK and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The Auth0 Go SDK is expecting a different JSON schema than what is returned from the API for the ListAuthenticationMethods API endpoint.

Response sample from Management API V2 endpoint:
```
[
    {
        "id": "phone|dev_sampleid",
        "type": "phone",
        "confirmed": true,
        "phone_number": "XXXXXXXX1234",
        "created_at": "2023-07-13T20:24:42.388Z",
        "last_auth_at": "2023-07-13T20:28:49.095Z",
        "preferred_authentication_method": "sms",
        "authentication_methods": [
            {
                "id": "sms|dev_sampleid",
                "type": "sms"
            }
        ]
    }
]

```

Error message from Auth0 Management GO SDK Call:

`failed to unmarshal response payload: json: cannot unmarshal array into Go value of type management.AuthenticationMethodList`

### Expectation

The SDK is expecting a wrapping authenticators parent object wrapping around the array of authentication methods, for example:

```

{
    "authenticators": [
      {
          "id": "phone|dev_sampleid",
          "type": "phone",
          "confirmed": true,
          "phone_number": "XXXXXXXX1234",
          "created_at": "2023-07-13T20:24:42.388Z",
          "last_auth_at": "2023-07-13T20:28:49.095Z",
          "preferred_authentication_method": "sms",
          "authentication_methods": [
              {
                  "id": "sms|dev_sampleid",
                  "type": "sms"
              }
          ]
      }
   ]
}
```

I would expect the SDK to be able to handle the latest version of the Auth0 Management API.

### Reproduction

1. Given a user who is enrolled with one or more Authentication factors in an Auth0 Tenant.
2. When you call the ListAuthenticationMethods function, providing the user ID from step 1, then ....
3. You receive the error "`failed to unmarshal response payload: json: cannot unmarshal array into Go value of type management.AuthenticationMethodList`"

### Auth0 Go SDK version

0.17.2

**Comment by ewanharris** [comment] 2023-07-17 16:14
Hey @mparz111, thank you for raising this issue.

We've investigated this and it appears that the root cause is the API no longer returning the expected structure when `include_totals` is set. This has been escalated to the relevant team and we're waiting on a fix.

I'll leave this issue open until I can provide some further feedback.

**Comment by MFFoX** [comment] 2023-07-17 17:24
@ewanharris Thanks for the response. Can you provide a sample curl request to Management API endpoint that responds with the json structure that the SDK is expecting? I am wanting to make sure I understand this functionality.

**Comment by ewanharris** [comment] 2023-07-18 06:22
@MFFoX, unfortunately because of the issue mentioned it's not possible to currently get the data in the expected response format. However, an example curl that would correspond to this normally is `https://<auth0-domain>/api/v2/users/<user-id>/authentication-methods?include_totals=true&per_page=50`, it's the addition of the `include_totals` (that the Go SDK expects) that changes the response format.

It is similar to the format mentioned in the issue body, with the addition of pagination data, you can find all potential properties for the different authentication methods in the [API docs](https://auth0.com/docs/api/management/v2#!/Users/get_authentication_methods)

```
{
    "authenticators": [
        {
            "id": "email|dev_test",
            "type": "email",
            "confirmed": true,
            "name": "Test",
            "email": "chuc****@exam*******",
            "created_at": "2023-03-10T16:25:51.113Z"
        }
    ],
    "total": 1,
    "start": 0,
    "limit": 50
}
```

**Comment by ewanharris** [comment] 2023-08-02 11:34
@mparz111 @MFFoX, just a heads up that the fix for the change in response should be rolling out to all environments so I believe this issue should now be resolved.

**Comment by mparz111** [comment] 2023-08-02 14:54
Thanks @ewanharris!

Was the fix made with the API or the SDK?

**Comment by ewanharris** [comment] 2023-08-03 09:15
This was an API side fix to restore the pagination headers in the response

**Comment by ewanharris** [comment] 2023-08-09 08:53
Closing this issue out now as it's resolved.

**Closed by ewanharris** 2023-08-09 08:53 UTC
Labels: bug
